import csv
import random
import pandas as pd

with open('synth_data_module/snomedbasicmappings.csv') as f:
    next(f)  # Skip the header
    reader = csv.reader(f, skipinitialspace=True)
    snomeddict = dict(reader)

with open('StudyOverrides/LARC/hospitals.csv') as f:
    next(f)  # Skip the header
    reader = csv.reader(f, skipinitialspace=True)
    HCAImap = {rows[2]: rows[19] for rows in reader}


def ethnicity(col):
    dic = {'hispanic': 'E1',
           'nonhispanic': 'E2'}
    col = col.apply(lambda x: dic.get(x, '99'))
    return col


def gender(col):
    dic = {'M': 'M',
           'F': 'F'}
    col = col.apply(lambda x: dic.get(x, 'U'))
    return col


def languagewritein(col):
    language_list = ['English', 'Spanish', 'Mandarin', 'Tagalog', 'Vietnamese', 'Korean', 'Farsi', 'Armenian', 'Arabic',
                     'Hindi']
    language_weights = (58.2, 28.8, 3.2, 2.2, 1.5, 1, 0.5, 0.5, 0.5, 0.5)
    col = col.apply(lambda x: random.choices(language_list, weights=language_weights)[0] if pd.isnull(x) else x)
    return col


def language(col):
    dic = {
            'English': 'ENG',
            'Spanish': 'SPA',
            'Mandarin': 'CMN',
            'Tagalog': 'TGL',
            'Vietnamese': 'VIE',
            'Korean': 'KOR',
            'Farsi': 'PES',
            'Armenian': 'ARM',
            'Arabic': 'ARA',
            'Hindi': 'HIN',
            '': ''
            }
    col = col.apply(lambda x: dic.get(x, '-'))
    return col


def larcsnomedmap(col):
    dic = {'65200003':  {'0UH97HZ': 99, '0UH98HZ': 1},
           '169553002': {'0JHD3HZ': 10, '0JHF3HZ': 90},
           }
    col = col.apply(lambda x: random.choices(list(dic.get(x, {x: x}).keys()),
                                             weights=tuple(dic.get(x, {x: 1}).values()))[0])
    return col


def cov_to_pay_type(col):
    dic = {
        'HMO': '1',
        'PPO': '2',
        'EPO': '2',
        'POS': '2',
    }
    col = col.apply(lambda x: dic.get(x, '-'))
    return col


def hmo_plan_codes(col):
    dic = {
        'Humana': '0476',
        'Blue Cross Blue Shield': '0043',
        'UnitedHealthcare': '0126',
        'Aetna': '0176',
        'Cigna Health': '0152',
        'Anthem': '0303',
        'Kaiser': '0055',
    }
    col = col.apply(lambda x: dic.get(x, '0000'))
    return col


def payer_category(df):
    govdic = {'medicare': '01',
              'medi-cal': '02',
              'medical': '02',
              # Designate dual eligible payers as medicare:
              'dual eligible': '01',
              # County Indigent Programs : '05',
              }
    privdic = {
           # Workers’ Compensation : '04',
           # Other Indigent : '07',
           }
    # If Gov owned payer identify if medicare or medical, otherwise return 06 ('OTHER Gov'). lower match for accuracy
    if df[2] in ['GOVERNMENT', ]:
        category = govdic.get(df[1].lower(), '06')
    # If Private owned, look up specific designations (to be added as necessary) otherwise return 03 = private coverage
    elif df[2] in ['PRIVATE', ]:
        category = privdic.get(df[1], '03')
    # Return Self Pay if NO_INSURANCE
    elif df[2] in ['NO_INSURANCE', ]:
        category = '08'
    else:
        category = '09'
    return category


def drg_catagories(col):
    dic = {'788': '788',  # CESAREAN SECTION WITHOUT STERILIZATION WITHOUT CC/MCC
           '768': '768',  # VAGINAL DELIVERY WITH O.R. PROCEDURE EXCEPT STERILIZATION AND/OR D&C
           '807': '807'}  # VAGINAL DELIVERY WITHOUT STERILIZATION OR D&C WITHOUT CC/MCC
    col = col.apply(lambda x: dic.get(x, ''))
    return col


def race(col):
    dic = {'native': 'R1',
           'asian': 'R2',
           'black': 'R3',
           'hawaiian': 'R4',
           'white': 'R5',
           'other': 'R9'}
    col = col.apply(lambda x: dic.get(x, '99'))
    return col


def disposition():
    opts = ['01', '02', '03', '04', '05', '06', '07', '20', '21', '43', '50', '51', '61', '62', '63', '64', '65', '66',
            '69', '70', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '00']
    return opts


def snomedicdbasicmap(col):
    dic = snomeddict
    col = col.apply(lambda x: dic.get(x, ''))
    return col


def hcai(col, length):
    dic = HCAImap
    col = col.apply(lambda x: dic.get(x, '')[-length:])
    return col


def CAcounty(col):
    dic = {'Invalid': '-',
           'Not a California county Unknown or Homeless': '00',
           'Alameda': '01',
           'Alpine': '02',
           'Amador': '03',
           'Butte': '04',
           'Calaveras': '05',
           'Colusa': '06',
           'Contra Costa': '07',
           'Del Norte': '08',
           'El Dorado': '09',
           'Fresno': '10',
           'Glenn': '11',
           'Humboldt': '12',
           'Imperial': '13',
           'Inyo': '14',
           'Kern': '15',
           'Kings': '16',
           'Lake': '17',
           'Lassen': '18',
           'Los Angeles': '19',
           'Madera': '20',
           'Marin': '21',
           'Mariposa': '22',
           'Mendocino': '23',
           'Merced': '24',
           'Modoc': '25',
           'Mono': '26',
           'Monterey': '27',
           'Napa': '28',
           'Nevada': '29',
           'Orange': '30',
           'Placer': '31',
           'Plumas': '32',
           'Riverside': '33',
           'Sacramento': '34',
           'San Benito': '35',
           'San Bernardino': '36',
           'San Diego': '37',
           'San Francisco': '38',
           'San Joaquin': '39',
           'San Luis Obispo': '40',
           'San Mateo': '41',
           'Santa Barbara': '42',
           'Santa Clara': '43',
           'Santa Cruz': '44',
           'Shasta': '45',
           'Sierra': '46',
           'Siskiyou': '47',
           'Solano': '48',
           'Sonoma': '49',
           'Stanislaus': '50',
           'Sutter': '51',
           'Tehama': '52',
           'Trinity': '53',
           'Tulare': '54',
           'Tuolumne': '55',
           'Ventura': '56',
           'Yolo': '57',
           'Yuba': '58',
           pd.NA: ' ',
           }
    if type(col) == str:
        col = dic[col]
    else:
        col = col.apply(lambda x: dic.get(x.replace(" County", ""), '00'))
    return col


def CAcity(col):
    dic = {
        'Adelanto': 'San Bernardino',
        'Agoura Hills': 'Los Angeles',
        'Alameda': 'Alameda',
        'Albany': 'Alameda',
        'Alhambra': 'Los Angeles',
        'Aliso Viejo': 'Orange',
        'Alturas': 'Modoc',
        'Amador City': 'Amador',
        'American Canyon': 'Napa',
        'Anaheim': 'Orange',
        'Anderson': 'Shasta',
        'Angels': 'Calaveras',
        'Antioch': 'Contra Costa',
        'Apple Valley': 'San Bernardino',
        'Arcadia': 'Los Angeles',
        'Arcata': 'Humboldt',
        'Arroyo Grande': 'San Luis Obispo',
        'Artesia': 'Los Angeles',
        'Arvin': 'Kern',
        'Atascadero': 'San Luis Obispo',
        'Atherton': 'San Mateo',
        'Atwater': 'Merced',
        'Auburn': 'Placer',
        'Avalon': 'Los Angeles',
        'Avenal': 'Kings',
        'Azusa': 'Los Angeles',
        'Bakersfield': 'Kern',
        'Baldwin Park': 'Los Angeles',
        'Banning': 'Riverside',
        'Barstow': 'San Bernardino',
        'Beaumont': 'Riverside',
        'Bell': 'Los Angeles',
        'Bell Gardens': 'Los Angeles',
        'Bellflower': 'Los Angeles',
        'Belmont': 'San Mateo',
        'Belvedere': 'Marin',
        'Benicia': 'Solano',
        'Berkeley': 'Alameda',
        'Beverly Hills': 'Los Angeles',
        'Big Bear Lake': 'San Bernardino',
        'Biggs': 'Butte',
        'Bishop': 'Inyo',
        'Blue Lake': 'Humboldt',
        'Blythe': 'Riverside',
        'Bradbury': 'Los Angeles',
        'Brawley': 'Imperial',
        'Brea': 'Orange',
        'Brentwood': 'Contra Costa',
        'Brisbane': 'San Mateo',
        'Buellton': 'Santa Barbara',
        'Buena Park': 'Orange',
        'Burbank': 'Los Angeles',
        'Burlingame': 'San Mateo',
        'Calabasas': 'Los Angeles',
        'Calexico': 'Imperial',
        'California': 'Kern',
        'Calimesa': 'Riverside',
        'Calipatria': 'Imperial',
        'Calistoga': 'Napa',
        'Camarillo': 'Ventura',
        'Campbell': 'Santa Clara',
        'Canyon Lake': 'Riverside',
        'Capitola': 'Santa Cruz',
        'Carlsbad': 'San Diego',
        'Carmel-by-the-Sea': 'Monterey',
        'Carpinteria': 'Santa Barbara',
        'Carson': 'Los Angeles',
        'Cathedral City': 'Riverside',
        'Ceres': 'Stanislaus',
        'Cerritos': 'Los Angeles',
        'Chico': 'Butte',
        'Chino': 'San Bernardino',
        'Chino Hills': 'San Bernardino',
        'Chowchilla': 'Madera',
        'Chula Vista': 'San Diego',
        'Citrus Heights': 'Sacramento',
        'Claremont': 'Los Angeles',
        'Clayton': 'Contra Costa',
        'Clearlake': 'Lake',
        'Cloverdale': 'Sonoma',
        'Clovis': 'Fresno',
        'Coachella': 'Riverside',
        'Coalinga': 'Fresno',
        'Colfax': 'Placer',
        'Colma': 'San Mateo',
        'Colton': 'San Bernardino',
        'Colusa': 'Colusa',
        'Commerce': 'Los Angeles',
        'Compton': 'Los Angeles',
        'Concord': 'Contra Costa',
        'Corcoran': 'Kings',
        'Corning': 'Tehama',
        'Corona': 'Riverside',
        'Coronado': 'San Diego',
        'Corte Madera': 'Marin',
        'Costa Mesa': 'Orange',
        'Cotati': 'Sonoma',
        'Covina': 'Los Angeles',
        'Crescent City': 'Del Norte',
        'Cudahy': 'Los Angeles',
        'Culver City': 'Los Angeles',
        'Cupertino': 'Santa Clara',
        'Cypress': 'Orange',
        'Daly City': 'San Mateo',
        'Dana Point': 'Orange',
        'Danville': 'Contra Costa',
        'Davis': 'Yolo',
        'Del Mar': 'San Diego',
        'Del Rey Oaks': 'Monterey',
        'Delano': 'Kern',
        'Desert Hot Springs': 'Riverside',
        'Diamond Bar': 'Los Angeles',
        'Dinuba': 'Tulare',
        'Dixon': 'Solano',
        'Dorris': 'Siskiyou',
        'Dos Palos': 'Merced',
        'Downey': 'Los Angeles',
        'Duarte': 'Los Angeles',
        'Dublin': 'Alameda',
        'Dunsmuir': 'Siskiyou',
        'East Palo Alto': 'San Mateo',
        'Eastvale': 'Riverside',
        'El Cajon': 'San Diego',
        'El Centro': 'Imperial',
        'El Cerrito': 'Contra Costa',
        'El Monte': 'Los Angeles',
        'El Segundo': 'Los Angeles',
        'Elk Grove': 'Sacramento',
        'Emeryville': 'Alameda',
        'Encinitas': 'San Diego',
        'Escalon': 'San Joaquin',
        'Escondido': 'San Diego',
        'Etna': 'Siskiyou',
        'Eureka': 'Humboldt',
        'Exeter': 'Tulare',
        'Fairfax': 'Marin',
        'Fairfield': 'Solano',
        'Farmersville': 'Tulare',
        'Ferndale': 'Humboldt',
        'Fillmore': 'Ventura',
        'Firebaugh': 'Fresno',
        'Folsom': 'Sacramento',
        'Fontana': 'San Bernardino',
        'Fort Bragg': 'Mendocino',
        'Fort Jones': 'Siskiyou',
        'Fortuna': 'Humboldt',
        'Foster City': 'San Mateo',
        'Fountain Valley': 'Orange',
        'Fowler': 'Fresno',
        'Fremont': 'Alameda',
        'Fresno': 'Fresno',
        'Fullerton': 'Orange',
        'Galt': 'Sacramento',
        'Garden Grove': 'Orange',
        'Gardena': 'Los Angeles',
        'Gilroy': 'Santa Clara',
        'Glendale': 'Los Angeles',
        'Glendora': 'Los Angeles',
        'Goleta': 'Santa Barbara',
        'Gonzales': 'Monterey',
        'Grand Terrace': 'San Bernardino',
        'Grass Valley': 'Nevada',
        'Greenfield': 'Monterey',
        'Gridley': 'Butte',
        'Grover Beach': 'San Luis Obispo',
        'Guadalupe': 'Santa Barbara',
        'Gustine': 'Merced',
        'Half Moon Bay': 'San Mateo',
        'Hanford': 'Kings',
        'Hawaiian Gardens': 'Los Angeles',
        'Hawthorne': 'Los Angeles',
        'Hayward': 'Alameda',
        'Healdsburg': 'Sonoma',
        'Hemet': 'Riverside',
        'Hercules': 'Contra Costa',
        'Hermosa Beach': 'Los Angeles',
        'Hesperia': 'San Bernardino',
        'Hidden Hills': 'Los Angeles',
        'Highland': 'San Bernardino',
        'Hillsborough': 'San Mateo',
        'Hollister': 'San Benito',
        'Holtville': 'Imperial',
        'Hughson': 'Stanislaus',
        'Huntington Beach': 'Orange',
        'Huntington Park': 'Los Angeles',
        'Huron': 'Fresno',
        'Imperial': 'Imperial',
        'Imperial Beach': 'San Diego',
        'Indian Wells': 'Riverside',
        'Indio': 'Riverside',
        'Industry': 'Los Angeles',
        'Inglewood': 'Los Angeles',
        'Ione': 'Amador',
        'Irvine': 'Orange',
        'Irwindale': 'Los Angeles',
        'Isleton': 'Sacramento',
        'Jackson': 'Amador',
        'Jurupa Valley': 'Riverside',
        'Kerman': 'Fresno',
        'King City': 'Monterey',
        'Kingsburg': 'Fresno',
        'La Cañada Flintridge': 'Los Angeles',
        'La Habra': 'Orange',
        'La Habra Heights': 'Los Angeles',
        'La Mesa': 'San Diego',
        'La Mirada': 'Los Angeles',
        'La Palma': 'Orange',
        'La Puente': 'Los Angeles',
        'La Quinta': 'Riverside',
        'La Verne': 'Los Angeles',
        'Lafayette': 'Contra Costa',
        'Laguna Beach': 'Orange',
        'Laguna Hills': 'Orange',
        'Laguna Niguel': 'Orange',
        'Laguna Woods': 'Orange',
        'Lake Elsinore': 'Riverside',
        'Lake Forest': 'Orange',
        'Lakeport': 'Lake',
        'Lakewood': 'Los Angeles',
        'Lancaster': 'Los Angeles',
        'Larkspur': 'Marin',
        'Lathrop': 'San Joaquin',
        'Lawndale': 'Los Angeles',
        'Lemon Grove': 'San Diego',
        'Lemoore': 'Kings',
        'Lincoln': 'Placer',
        'Lindsay': 'Tulare',
        'Live Oak': 'Sutter',
        'Livermore': 'Alameda',
        'Livingston': 'Merced',
        'Lodi': 'San Joaquin',
        'Loma Linda': 'San Bernardino',
        'Lomita': 'Los Angeles',
        'Lompoc': 'Santa Barbara',
        'Long Beach': 'Los Angeles',
        'Loomis': 'Placer',
        'Los Alamitos': 'Orange',
        'Los Altos': 'Santa Clara',
        'Los Altos Hills': 'Santa Clara',
        'Los Angeles': 'Los Angeles',
        'Los Banos': 'Merced',
        'Los Gatos': 'Santa Clara',
        'Loyalton': 'Sierra',
        'Lynwood': 'Los Angeles',
        'Madera': 'Madera',
        'Malibu': 'Los Angeles',
        'Mammoth Lakes': 'Mono',
        'Manhattan Beach': 'Los Angeles',
        'Manteca': 'San Joaquin',
        'Maricopa': 'Kern',
        'Marina': 'Monterey',
        'Martinez': 'Contra Costa',
        'Marysville': 'Yuba',
        'Maywood': 'Los Angeles',
        'McFarland': 'Kern',
        'Mendota': 'Fresno',
        'Menifee': 'Riverside',
        'Menlo Park': 'San Mateo',
        'Merced': 'Merced',
        'Mill Valley': 'Marin',
        'Millbrae': 'San Mateo',
        'Milpitas': 'Santa Clara',
        'Mission Viejo': 'Orange',
        'Modesto': 'Stanislaus',
        'Monrovia': 'Los Angeles',
        'Montague': 'Siskiyou',
        'Montclair': 'San Bernardino',
        'Monte Sereno': 'Santa Clara',
        'Montebello': 'Los Angeles',
        'Monterey': 'Monterey',
        'Monterey Park': 'Los Angeles',
        'Moorpark': 'Ventura',
        'Moraga': 'Contra Costa',
        'Moreno Valley': 'Riverside',
        'Morgan Hill': 'Santa Clara',
        'Morro Bay': 'San Luis Obispo',
        'Mount Shasta': 'Siskiyou',
        'Mountain View': 'Santa Clara',
        'Murrieta': 'Riverside',
        'Napa': 'Napa',
        'National City': 'San Diego',
        'Needles': 'San Bernardino',
        'Nevada City': 'Nevada',
        'Newark': 'Alameda',
        'Newman': 'Stanislaus',
        'Newport Beach': 'Orange',
        'Norco': 'Riverside',
        'Norwalk': 'Los Angeles',
        'Novato': 'Marin',
        'Oakdale': 'Stanislaus',
        'Oakland': 'Alameda',
        'Oakley': 'Contra Costa',
        'Oceanside': 'San Diego',
        'Ojai': 'Ventura',
        'Ontario': 'San Bernardino',
        'Orange': 'Orange',
        'Orange Cove': 'Fresno',
        'Orinda': 'Contra Costa',
        'Orland': 'Glenn',
        'Oroville': 'Butte',
        'Oxnard': 'Ventura',
        'Pacific Grove': 'Monterey',
        'Pacifica': 'San Mateo',
        'Palm Desert': 'Riverside',
        'Palm Springs': 'Riverside',
        'Palmdale': 'Los Angeles',
        'Palo Alto': 'Santa Clara',
        'Palos Verdes Estates': 'Los Angeles',
        'Paradise': 'Butte',
        'Paramount': 'Los Angeles',
        'Parlier': 'Fresno',
        'Pasadena': 'Los Angeles',
        'Paso Robles': 'San Luis Obispo',
        'Patterson': 'Stanislaus',
        'Perris': 'Riverside',
        'Petaluma': 'Sonoma',
        'Pico Rivera': 'Los Angeles',
        'Piedmont': 'Alameda',
        'Pinole': 'Contra Costa',
        'Pismo Beach': 'San Luis Obispo',
        'Pittsburg': 'Contra Costa',
        'Placentia': 'Orange',
        'Placerville': 'El Dorado',
        'Pleasant Hill': 'Contra Costa',
        'Pleasanton': 'Alameda',
        'Plymouth': 'Amador',
        'Point Arena': 'Mendocino',
        'Pomona': 'Los Angeles',
        'Port Hueneme': 'Ventura',
        'Porterville': 'Tulare',
        'Portola': 'Plumas',
        'Portola Valley': 'San Mateo',
        'Poway': 'San Diego',
        'Rancho Cordova': 'Sacramento',
        'Rancho Cucamonga': 'San Bernardino',
        'Rancho Mirage': 'Riverside',
        'Rancho Palos Verdes': 'Los Angeles',
        'Rancho Santa Margarita': 'Orange',
        'Red Bluff': 'Tehama',
        'Redding': 'Shasta',
        'Redlands': 'San Bernardino',
        'Redondo Beach': 'Los Angeles',
        'Redwood City': 'San Mateo',
        'Reedley': 'Fresno',
        'Rialto': 'San Bernardino',
        'Richmond': 'Contra Costa',
        'Ridgecrest': 'Kern',
        'Rio Dell': 'Humboldt',
        'Rio Vista': 'Solano',
        'Ripon': 'San Joaquin',
        'Riverbank': 'Stanislaus',
        'Riverside': 'Riverside',
        'Rocklin': 'Placer',
        'Rohnert Park': 'Sonoma',
        'Rolling Hills': 'Los Angeles',
        'Rolling Hills Estates': 'Los Angeles',
        'Rosemead': 'Los Angeles',
        'Roseville': 'Placer',
        'Ross': 'Marin',
        'Sacramento': 'Sacramento',
        'Salinas': 'Monterey',
        'San Anselmo': 'Marin',
        'San Bernardino': 'San Bernardino',
        'San Bruno': 'San Mateo',
        'San Carlos': 'San Mateo',
        'San Clemente': 'Orange',
        'San Diego': 'San Diego',
        'San Dimas': 'Los Angeles',
        'San Fernando': 'Los Angeles',
        'San Francisco': 'San Francisco',
        'San Gabriel': 'Los Angeles',
        'San Jacinto': 'Riverside',
        'San Joaquin': 'Fresno',
        'San Jose': 'Santa Clara',
        'San Juan Bautista': 'San Benito',
        'San Juan Capistrano': 'Orange',
        'San Leandro': 'Alameda',
        'San Luis Obispo': 'San Luis Obispo',
        'San Marcos': 'San Diego',
        'San Marino': 'Los Angeles',
        'San Mateo': 'San Mateo',
        'San Pablo': 'Contra Costa',
        'San Rafael': 'Marin',
        'San Ramon': 'Contra Costa',
        'Sand City': 'Monterey',
        'Sanger': 'Fresno',
        'Santa Ana': 'Orange',
        'Santa Barbara': 'Santa Barbara',
        'Santa Clara': 'Santa Clara',
        'Santa Clarita': 'Los Angeles',
        'Santa Cruz': 'Santa Cruz',
        'Santa Fe Springs': 'Los Angeles',
        'Santa Maria': 'Santa Barbara',
        'Santa Monica': 'Los Angeles',
        'Santa Paula': 'Ventura',
        'Santa Rosa': 'Sonoma',
        'Santee': 'San Diego',
        'Saratoga': 'Santa Clara',
        'Sausalito': 'Marin',
        'Scotts Valley': 'Santa Cruz',
        'Seal Beach': 'Orange',
        'Seaside': 'Monterey',
        'Sebastopol': 'Sonoma',
        'Selma': 'Fresno',
        'Shafter': 'Kern',
        'Shasta Lake': 'Shasta',
        'Sierra Madre': 'Los Angeles',
        'Signal Hill': 'Los Angeles',
        'Simi Valley': 'Ventura',
        'Solana Beach': 'San Diego',
        'Soledad': 'Monterey',
        'Solvang': 'Santa Barbara',
        'Sonoma': 'Sonoma',
        'Sonora': 'Tuolumne',
        'South El Monte': 'Los Angeles',
        'South Gate': 'Los Angeles',
        'South Lake Tahoe': 'El Dorado',
        'South Pasadena': 'Los Angeles',
        'South San Francisco': 'San Mateo',
        'St. Helena': 'Napa',
        'Stanton': 'Orange',
        'Stockton': 'San Joaquin',
        'Suisun City': 'Solano',
        'Sunnyvale': 'Santa Clara',
        'Susanville': 'Lassen',
        'Sutter Creek': 'Amador',
        'Taft': 'Kern',
        'Tehachapi': 'Kern',
        'Tehama': 'Tehama',
        'Temecula': 'Riverside',
        'Temple City': 'Los Angeles',
        'Thousand Oaks': 'Ventura',
        'Tiburon': 'Marin',
        'Torrance': 'Los Angeles',
        'Tracy': 'San Joaquin',
        'Trinidad': 'Humboldt',
        'Truckee': 'Nevada',
        'Tulare': 'Tulare',
        'Tulelake': 'Siskiyou',
        'Turlock': 'Stanislaus',
        'Tustin': 'Orange',
        'Twentynine Palms': 'San Bernardino',
        'Ukiah': 'Mendocino',
        'Union City': 'Alameda',
        'Upland': 'San Bernardino',
        'Vacaville': 'Solano',
        'Vallejo': 'Solano',
        'Ventura': 'Ventura',
        'Vernon': 'Los Angeles',
        'Victorville': 'San Bernardino',
        'Villa Park': 'Orange',
        'Visalia': 'Tulare',
        'Vista': 'San Diego',
        'Walnut': 'Los Angeles',
        'Walnut Creek': 'Contra Costa',
        'Wasco': 'Kern',
        'Waterford': 'Stanislaus',
        'Watsonville': 'Santa Cruz',
        'Weed': 'Siskiyou',
        'West Covina': 'Los Angeles',
        'West Hollywood': 'Los Angeles',
        'West Sacramento': 'Yolo',
        'Westlake Village': 'Los Angeles',
        'Westminster': 'Orange',
        'Westmorland': 'Imperial',
        'Wheatland': 'Yuba',
        'Whittier': 'Los Angeles',
        'Wildomar': 'Riverside',
        'Williams': 'Colusa',
        'Willits': 'Mendocino',
        'Willows': 'Glenn',
        'Windsor': 'Sonoma',
        'Winters': 'Yolo',
        'Woodlake': 'Tulare',
        'Woodland': 'Yolo',
        'Woodside': 'San Mateo',
        'Yorba Linda': 'Orange',
        'Yountville': 'Napa',
        'Yreka': 'Siskiyou',
        'Yuba City': 'Sutter',
        'Yucaipa': 'San Bernardino',
        'Yucca Valley': 'San Bernardino',
        }
    col = col.apply(lambda x: dic.get(x.title(), 'Los Angeles'))
    return CAcounty(col)
